### ISSUE TITLE
python GUIは可能ですか？

### ISSUE THREAD

**Issue by revTimo** [jpki/myna#2]
python GUI で作りたいですが、可能ですか？　２週間前から始めたんですが、カードをカードをどうやってreadさせるかをできないですが、教えていただけますか？

**Comment by hamano** [comment]
このmynaは単独のアプリケーションとして提供しているので、ライブラリとして使われることを想定していないです。
Pythonアプリケーションを開発するのであれば、OpenSCのPKCS#11 ライブラリ経由でカードにアクセスできます。
GUIはPyQtとかwxPythonとかお好きなのを使えば良いんじゃないでしょうか、
参考:
https://www.capa.co.jp/archives/15308
